import type { AIPoseSuggestion } from '../types/camera';

/**
 * Initial Starter Pose:
 * Explains how the AI Director works before the user triggers scene analysis.
 * No hardcoded pose catalogue! All poses are dynamically generated by Gemini + Text-to-Image AI.
 */
export const WELCOME_POSE: AIPoseSuggestion = {
  id: 'welcome_pose',
  title: 'AI Scene Director',
  vibe: 'Custom AI Generation',
  directionTip: 'Tap "✨ Pose Me" below! The AI will analyze your surrounding furniture and scene objects to generate a custom pose photo tailored for you.',
  sceneObjects: ['Your Environment & Props'],
  imagePrompt: 'A stylish person in a modern setting striking a flattering natural photography pose, professional portrait',
  referenceImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
  createdAt: Date.now(),
  cameraFacing: 'environment',
};
